name: CI

on:
  push:
    branches: [main, dev]
<<<<<<< HEAD
  pull_request:
    branches: [main, dev]
=======
>>>>>>> 009cca76e5ac60ae407de0440bad4a584a95e07f

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

<<<<<<< HEAD
      - name: Build all apps
=======
      - name: Lint
        run: pnpm lint

      - name: Build
>>>>>>> 009cca76e5ac60ae407de0440bad4a584a95e07f
        run: pnpm build
